version: "3.7"

services:
  php:
    build: .
    container_name: php
    ports:
      - 80:80
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourPasswordHere
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql

volumes:
  db-vol:
